// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZkWiv9oeFaigpq4gxVSII9M19kdfgPvg',
    appId: '1:193488700812:web:483d81c8373471ce1a02a9',
    messagingSenderId: '193488700812',
    projectId: 'flutter-test-c057d',
    authDomain: 'flutter-test-c057d.firebaseapp.com',
    storageBucket: 'flutter-test-c057d.firebasestorage.app',
    measurementId: 'G-VX0XL2D5D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYySBCDRuRQrADtBrgiSxGqmny5sWuE7Q',
    appId: '1:193488700812:android:89b250125b03c6f71a02a9',
    messagingSenderId: '193488700812',
    projectId: 'flutter-test-c057d',
    storageBucket: 'flutter-test-c057d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjyjlYy5b-5PSVXhSsrHwULIxmRIp4lko',
    appId: '1:193488700812:ios:4357aaa076b1250a1a02a9',
    messagingSenderId: '193488700812',
    projectId: 'flutter-test-c057d',
    storageBucket: 'flutter-test-c057d.firebasestorage.app',
    iosBundleId: 'com.example.flutterTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjyjlYy5b-5PSVXhSsrHwULIxmRIp4lko',
    appId: '1:193488700812:ios:4357aaa076b1250a1a02a9',
    messagingSenderId: '193488700812',
    projectId: 'flutter-test-c057d',
    storageBucket: 'flutter-test-c057d.firebasestorage.app',
    iosBundleId: 'com.example.flutterTest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZkWiv9oeFaigpq4gxVSII9M19kdfgPvg',
    appId: '1:193488700812:web:ea77c6812568f2181a02a9',
    messagingSenderId: '193488700812',
    projectId: 'flutter-test-c057d',
    authDomain: 'flutter-test-c057d.firebaseapp.com',
    storageBucket: 'flutter-test-c057d.firebasestorage.app',
    measurementId: 'G-KW4KBY5Y2F',
  );
}
